### ISSUE TITLE
RPC-API: Generic status message notification

### ISSUE THREAD

**Issue by gabriel** [keybase/go-libkb#71]
Instead of using keybase.1.identifyUi.warning for status messages maybe we should have a generic method that works for any method (namespace).

Maybe we should have a:
keybase.1.statusUi.message(level, message)

And perhaps it should be a (msgpack rpc) notification (type=3 in https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md)

**Comment by maxtaco** [comment]
Agreed. I had something in progress over in [this branch](https://github.com/keybase/go-client/tree/issue_20) but that it a few bugs down in my current bug stack.

Agreed about notify (msg type=2) but i havne't implemented it yet on the go side.  Made a big note that I had to though :)  We never actually have used it in the past.
